language: python
python:
- 3.6
install:
- pip3 install -r requirements.txt
script:
- coverage run test.py -v
after_success:
  - coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: kDq11MLkgjAiDTzPvlNTEYIeU5rc1pDHC6V3FXv8wHA4usMtv+q0fVQAwn6GJyXd0nSoMqiusqwOEZLfdz2b0vlB8CICP0t8WWurAwFNpWWXTS3MSlXFO5xmLIUYRKmp+pxXcOojEuvM1ilOOkDCa3N74sgm+q4RKrQr0ZbBFJe61ShwVX10PQeDty4XAneyUJS534gEqsDvTRkKiCrsBQhRl7GOQH+oEPF8E+FQVxBzocDe3Z2FUkz2eSmCdeHwNZtN2JAYhKGLjm6p0ek4v9RYECxZT5cRcn/KAJ/KbaQfO5hsBt4Zvr7TeUFE75nem76T6IJ9dGXUBcPfRmStaXqB1gYlVwVOe9DCSbTyEWcaobPifiw1Gi3Xv6HBLs5QHFLn5Z6ilaFzAngAsWEq1FpvUrNSxxh6v2OTRxIgdrLTppjj2+2N0EYrYszoZlw2qdypi56vaQ/zMtXeIDsQvPqhGYUT4mzytDYwgy1A08ygj/HRozU0gkHyWrToW4TYhrCJDXe0LuwkzZcZ6JkWuNhY+kWrjQE3cK4y/+cCWq+91Ky60bwdT82sSE6zihBAjM5XtZnPZrDT8fa7emKNP+pI4zboXTZLrK8j995wvKckNADB9G8ZCcjiqASDGH07UoCl3v/zTmgGAOWdIU3YYuLv2hmttQnFupeE/PWsEAU=
  skip_cleanup: true
  on:
    condition: $TRAVIS_PYTHON_VERSION == '3.6'
    repo: plasticuproject/fnv1a
