language: python
python:
- 3.6
install:
- pip3 install -r requirements.txt
script:
- coverage run test.py -v
after_success:
  - coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: KlMaNzbwO47CiNbx/lfLwbK8N9pvAyQlBUR3xTkCXLeMOuzB9vzkgjvUjtXg20ndqBGbDS5KN4Y9zBX9wwU7NHSVp4slCfaLWB22aGu9T5yiI/+ESp2uYR30a1ZSM1TrGKZT1sc2ihqFx05iX7m3xJX1CMbTaXqCBW/HCjatpV5UbCQWCQhlAm/Ipknwnee3JZYlWJmWwHvAZB81SFOG3n1tHpwdJh/nG3c1b5MiwfCMCfsKPh8GibdH6uoFKHBAvSUfksS5GEwGeW3Z40YGOeFaV5zPwWAjTcxGWUeSv8DdJokBjLlK3kcIlZp8qF58UCc9UWTvz+wXTnj29xA+lWpxAGkE4nSVniF/btxz2BuS3nWYM7oLnzg8WGdzq9y1cFqAArsXbSaUPL+DJDYP4BzxeQEc+mrGzrpRqOUm/TxaAnt4VFqenPvq5U042dF6CR+tlfntrr9eYVOCTQOR62q/wYlfbp0ZVrKWttHWbcX1T7sLc3WHKWH8GocLXsu7kp/d4028z7wv1LYyuFoTeGlRGdXUkbjSI95QkrWPLNorcUvg2xhawyxnKPmGA81tRn4+BJ8iW9DrBmsa+14o2ltHaBKqjazYX8EzExLCAtXNhAZ6MUWkE3hnmtBH71JsJ8dBKLz6/C737dbd630mbIO+1zXXIhd+3s8BtiCvRDs=
  skip_cleanup: true
  on:
    condition: $TRAVIS_PYTHON_VERSION == '3.6'
    repo: plasticuproject/fnv1a
